#!/bin/sh

# Copyright (c) 2021 Holger Weiss <holger@zedat.fu-berlin.de>.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script depends on GNU Tar, GNU sed, Git, and curl.

set -e
set -u

debug='false'
base_url='https://repo.hex.pm/tarballs'
deps_dir='_build/default/lib'
repo_dir="$PWD"
hex_dir='hex'
app_src='src/rebar.app.src.script'
config_script='rebar.config.script'
rebar3_vsn=$(git describe --tags | sed -e 's|upstream/||' -e 's|-g.*||')
myself=${0##*/}
known_deps='
    bbmustache
    certifi
    cf
    cth_readable
    erlware_commons
    eunit_formatters
    getopt
    providers
    relx
    ssl_verify_fun
'

debug()
{
    if [ "${debug-false}" != 'false' ]
    then
        echo "$myself: $*"
    fi
}

abort()
{
    echo >&2 "$myself: $*, aborting."
    exit 1
}

is_known_dep()
{
    dep=$1

    for known_dep in $known_deps
    do
        test "$dep" = "$known_dep" && return 0
    done
    return 1
}

check_license()
{
    app=$1
    license=$(sed -n 's/.*<<"licenses">>.*"\([^"]*\)".*/\1/p' 'metadata.config')

    if [ -n "$license" ]
    then
        debug "License of $app $vsn: $license"
    else
        abort "Cannot find license of $app"
    fi
}

get_index()
{
    files="_build rebar3 $hex_dir/hexpm"

    debug 'Building rebar3 to have it generate the package index file'
    rm -rf $files
    ./bootstrap
    ./rebar3 get-deps
    rm -rf $files
}

get_deps()
{
    sed -n 's/.*pkg, *<<"\([^"]*\)">>, *<<"\([^"]*\)">>.*/\1 \2/p' 'rebar.lock' |
        while read app vsn
        do
            app_dir="$repo_dir/$deps_dir/$app"
            tar="$app-$vsn.tar"
            if ! is_known_dep "$app"
            then
                abort "Dependency $app not in list of 'known_deps'."
            fi
            if ! [ -d "$app_dir" ]
            then
                files='contents.tar.gz metadata.config'
                debug "Fetching dependency: $app $vsn"
                mkdir "$app_dir"
                cd "$app_dir"
                curl -sSL "$base_url/$tar" | tar -xf - $files
                check_license "$app"
                tar -xzf 'contents.tar.gz'
                rm $files
                test -e 'rebar.lock' && get_deps
                cd "$OLDPWD"
            else
                debug "Dependency $app $vsn is available already."
            fi
        done
}

set_version()
{
    vsn=$1

    sed -i "s/{ *vsn, *\"git\"}/{vsn, \"$vsn\"}/" "$app_src"
}

if ! [ -e 'rebar.config' ] || ! [ -e 'bootstrap' ]
then
    abort "Please call this script from the repository's root directory"
fi

while getopts d opt
do
    case $opt in
    d) debug='true';;
    *) abort "Usage: $myself [-h]";;
    esac
done

get_index
debug "Creating directory: $deps_dir"
mkdir -p "$deps_dir"
get_deps
set_version "$rebar3_vsn"
rebar3_dir="rebar3-$rebar3_vsn"
rebar3_tar="$rebar3_dir.tar"
echo "$app_src export-ignore" >'.git/info/attributes'
git archive --format='tar' --prefix="$rebar3_dir/" 'HEAD' >"$rebar3_tar"
rm '.git/info/attributes'
tar --transform "s/^/$rebar3_dir\//" -rf \
    "$rebar3_tar" "$config_script" "$app_src" "$deps_dir" "$hex_dir"
gzip -f9 "$rebar3_tar"
debug "Created: $rebar3_tar.gz"
